Repository jupyter/accessibility, pull requests merged in 2022-07, with the labels that each got.

#97 Remove axeOptions in order to use defaults
  jupyter_accessibility/jupyter-axe/playwright.config.ts
  testing/jupyterlab/playwright.config.ts
Labels: type: enhancement 💅🏼

#101 📄 Add license header
  .gitignore
  .gitpod.yml
  .readthedocs.yaml
  LICENSE
  README.md
  docs/_config.yml
  docs/_toc.yml
  docs/requirements.txt
  dodo.py
  jupyter_accessibility/__init__.py
  jupyter_accessibility/__main__.py
  jupyter_accessibility/dodo.py
  jupyter_accessibility/jupyter-axe/jupyter_server_config.py
  jupyter_accessibility/jupyter-axe/playwright.config.ts
  jupyter_accessibility/jupyter-axe/requirements.txt
  jupyter_accessibility/project.py
  noxfile.py
  pa11y-jupyter/serve.py
  pyproject.toml
  repos.toml
  repos.yml
  testing/jupyterlab/environment.yml
  testing/jupyterlab/jupyter_server_config.py
  testing/jupyterlab/playwright.config.ts
  testing/jupyterlab/tests/axe-violations.test.ts
  testing/jupyterlab/tests/tab-loop-no-trap.test.ts
Labels: PR: needs review 👀, type: maintenance 🔨

#102 :fire: Remove unused files
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/gitpod-docker.yml
Labels: area: workflows, type: maintenance 🔨, area: CI 👷🏽‍♀️
