Repository jupyter/accessibility, pull requests merged in 2022-08, with the labels that each got.

#106 ENH - Improve docs structure and update content
  .gitignore
  .readthedocs.yaml
  ARCHITECTURE.md
  README.md
  docs/_config.yml
  docs/_static/logos/JupAccessColor.svg
  docs/_static/logos/JupAccessDark.svg
  docs/_static/logos/JupAccessLight.svg
  docs/_static/logos/jupyter_accessibility.png
  docs/_toc.yml
  docs/community/README.md
  docs/community/index.md
  docs/community/information.rst
  docs/community/meeting-minutes/2019-web4all-hackathon/hackathon-resources.md
  docs/community/meeting-minutes/2022-jupyter-accessibility-workshops/jupyter-accessibility-workshops.md
  docs/community/meeting-minutes/jupyterlab-accessibility-meetings/index.rst
  docs/community/meeting-minutes/lumino/walkthrough-phosphor-prs.md
  docs/conf.py
  docs/contribute/guide.md
  docs/contribute/index.md
  docs/contribute/skills.md
  docs/contribute/this-repo.md
  docs/developer/README.md
  docs/funding/README.md
  docs/funding/czi-grant-completed.md
  docs/funding/czi-grant-roadmap.md
  docs/funding/index.md
  docs/images/stephaniewalter-accessibility-compliance-levels-to-reach.jpeg
  docs/index.md
  docs/requirements.txt
  docs/resources/JupyterLab-a11y-statement.md
  docs/resources/map-jupyterlab-frontend-architecture/README.md
  docs/resources/team_guides.rst
  docs/resources/useful-resources.md
  noxfile.py
  pa11y-jupyter/dodo.py
  pa11y-jupyter/noxfile.py
  pa11y-jupyter/serve.py
  repos.toml
  repos.yml
Labels: type: enhancement 💅🏼, area: documentation 📖, status: work in progress 🏗, PR: needs review 👀

#108 Add GitHub Action for Read the Docs previews
  .github/workflows/docs-preview.yml
Labels: type: enhancement 💅🏼, area: documentation 📖, area: CI 👷🏽‍♀️

#110 Use Read the Docs action v1
  .github/workflows/docs-preview.yml
Labels: type: enhancement 💅🏼, area: dependencies 📦, area: CI 👷🏽‍♀️
